server:
  port: 8090

spring:
  application:
    name: pg-server

  datasource:
    url: jdbc:h2:mem:pgserver;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
    show-sql: true

logging:
  level:
    org.springframework: INFO
    app.backend.pgserver: DEBUG
